[workspace]
name = "dqy"
version = "0.1.0"
edition = "2021"
members = [ 
    "args", 
    "dns",
    "dqy",
    "error",
    "transport",
    "show"]
resolver = "2"

[workspace.package]
name = "dqy"
version = "0.1.0"  #:version
authors = ["Alain Viguier <dandyvica@gmail.com>"]
description = """
dqy is a DNS query tool inspired by dig, drill and dog.
"""
documentation = "https://github.com/dandyvica/dqy"
homepage = "https://github.com/dandyvica/dqy"
repository = "https://github.com/dandyvica/dqy"
keywords = ["dns"]
categories = ["command-line-utilities"]
license = "MIT"
autotests = false
edition = "2021"
rust-version = "1.75"
doctest = false

[workspace.dependencies]
bytes = "1.5.0"
env_logger = "0.10.1"
error = { path = "../error" }
http = "1.0.0"
log = "0.4.20"
mlua = { version = "0.9.4", features = [ "lua54", "serialize" ] }
reqwest = { version = "0.11.23", default-features = false, features = ["rustls-tls-webpki-roots", "blocking"] }
resolver = { git = "https://github.com/dandyvica/resolver.git" }
rustls = "0.22.2"
rustls-pki-types = "1.1.0"
serde = { version = "1.0.195", features = [ "derive" ] }
serde_json = { version = "1.0.111", features = ["preserve_order"] }
webpki-roots = "0.26.0"

[profile.release]
strip = "debuginfo"


