# [workspace.package]
# version = "0.1.0"
# authors = ["Alain Viguier <dandyvica@gmail.com>"]
# description = "A short description of my package"
# homepage = "https://github.com/dandyvica/dqy"
# repository = "https://github.com/dandyvica/dqy"

[workspace]
name = "dqy"
version = "0.1.0"
edition = "2021"
members = [ 
    "args", 
    "dns",
    "dqy",
    "error",
    "transport",
    "show"]
resolver = "2"

