[package]
name = "options"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dns = { path = "../dns" }
http = "1.0.0"
transport = { path = "../transport" }
