[package]
name = "transport"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.5.0"
error = { path = "../error" }
http = "1.0.0"
log = "0.4.20"
reqwest = { version = "0.11.23", default-features = false, features = ["rustls-tls-webpki-roots", "blocking"] }
rustls = "0.22.2"
rustls-pki-types = "1.1.0"
webpki-roots = "0.26.0"

