[package]
name = "args"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.8"
log = "0.4.20"
resolver = { git = "https://github.com/dandyvica/resolver.git" }
dns = { path = "../dns" }
idna = "0.4.0"
env_logger = "0.10.1"
