[package]
name = "error"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true

[lib]
doctest = false

[dependencies]
mlua.workspace = true
reqwest.workspace = true
resolver.workspace = true
rustls.workspace = true

